# databases:
#   - name: muucontrol_db
#     plan: free
#     databaseName: sistemarural
#     user: sistemarural_user
# desativado temporariamente por burrice minha

services:
  - type: web
    name: sistemarural
    env: python
    plan: free
    buildCommand: ./build.sh
    startCommand: PYTHONPATH=backend gunicorn sistemarural.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - fromGroup: muucontrol-env
