# Generated by Django 5.2 on 2025-05-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfil",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to="perfil_fotos/"),
        ),
    ]
