# Generated by Django 5.2 on 2025-05-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0002_perfil_foto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perfil",
            name="foto",
            field=models.ImageField(
                blank=True, null=True, upload_to="static/media/perfis/"
            ),
        ),
    ]
