# Generated by Django 5.2 on 2025-04-12 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ordenha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_id', models.CharField(max_length=50)),
                ('data', models.DateField()),
                ('quantidade_leite', models.DecimalField(decimal_places=2, max_digits=5)),
                ('periodo', models.CharField(choices=[('manhã', 'Manhã'), ('tarde', 'Tarde')], max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
