# Generated by Django 5.2 on 2025-05-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alimentacao", "0002_alimentacao_usuario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alimentacao",
            name="quantidade",
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
