# Generated by Django 5.2 on 2025-05-15 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saude", "0002_saude_usuario"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="saude",
            name="animal_id",
        ),
        migrations.RemoveField(
            model_name="saude",
            name="medicamento",
        ),
        migrations.RemoveField(
            model_name="saude",
            name="observacoes",
        ),
        migrations.RemoveField(
            model_name="saude",
            name="responsavel",
        ),
        migrations.RemoveField(
            model_name="saude",
            name="tipo_atendimento",
        ),
        migrations.AddField(
            model_name="saude",
            name="descricao",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="saude",
            name="proxima_dose",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="saude",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("vacina", "Vacinação"),
                    ("vermifugo", "Vermifugação"),
                    ("doenca", "Tratamento de doença"),
                    ("outros", "Outros"),
                ],
                default=2,
                max_length=30,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="saude",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
