# Generated by Django 5.2 on 2025-05-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ordenha", "0002_ordenha_usuario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordenha",
            name="quantidade_leite",
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
