# Generated by Django 5.2 on 2025-04-18 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_id', models.CharField(max_length=50)),
                ('data', models.DateField()),
                ('tipo_alimento', models.CharField(max_length=100)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
